
services:
  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: flockwatch
    expose:
      - 27017
    volumes:
      - mongodb_flock_watch:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:flockwatch@mongodb:27017/flockwatch?authSource=admin
      LOG_LEVEL: silly
      UPDATE_FREQUENCY: 24
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  
volumes:
  mongodb_flock_watch:
